### ISSUE TITLE
Fail to import base scraper

### ISSUE THREAD

**Issue by jdulotr** [Recidiviz/recidiviz-data#1024]
I just joined the project and trying to make scraper for us_tn_bledsoe. However when I run the test and I run into an error:

```bash
  File "/Users/jiameidu/projectcensus/recidiviz-data/recidiviz/ingest/scrape/regions/us_tn_bledsoe/us_tn_bledsoe_scraper.py", line 21, in <module>
    from recidiviz.ingest.base_scraper import BaseScraper
ModuleNotFoundError: No module named 'recidiviz.ingest.base_scraper'

INFO:root:***
INFO:root:The following regions raised errors during scraping: ['us_tn_bledsoe']

```
How should I fix it? Thank you!

**Comment by dmcc** [comment]
Try this instead:

    from recidiviz.ingest.scrape.base_scraper import BaseScraper

(I think it was moved around and the template needs to be updated)
