### ISSUE TITLE
Investigate index updates for session items

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#105]
After generalized ingest has been running in production for a while and we've gathered performance metrics, a likely place for optimization will be properly indexing reads from and writes to session management.

Measure latency and throughput of session queries and determine if there are index updates to make.

**Comment by ohinds** [comment]
@jessex is this still relevant?

**Comment by jessex** [comment]
I think we're still planning on using sessions going forward, but we generally don't need to open issues unless we are absolutely sure there is work to be done. Will close this.
