### ISSUE TITLE
Figure out schedule for prod-data backups

### ISSUE THREAD

**Issue by zdg2102** [Recidiviz/recidiviz-data#1113]
Cloud SQL automatically keeps daily backups for the last 7 days.

The two questions that follow from that are:
1) Do we want backups that are longer-term than that?
2) And if so, how many and how frequently do we want them?

Cloud SQL doesn't provide any way (at least that I've been able to find) of automatically scheduling longer-term backups. However, it does provide an option to manually request both creation and deletion of additional backups separate from the automatic 7-day backups. Since both creation and deletion can be requested via curl (https://cloud.google.com/sql/docs/postgres/backup-recovery/backing-up), I imagine we could set up some kind of cron to add and remove backups on some schedule.

**Comment by jessex** [comment]
I think it would be preferable, in the ideal with no cost consideration and no noticeable performance impact, to have backups created every night and kept for about two-three weeks. I think given the more constrained support resources, one week as an upper bound for performing a restore in a disaster situation is _doable_ but riskier than having a full-two weeks. If I had to prioritize between more frequent backups and backups kept for longer, I would lean in the direction of keeping backups for longer.

It would be easy to automatically schedule creation and deletion. What I would like to know, which I think you're in the best position to estimate @zdg2102, is how we think different backup lengths impact costs? How much would one week of backups cost when our database is 2x and 10x its current size, and how much would three weeks cost?

**Comment by zdg2102** [comment]
If you look at https://pantheon.corp.google.com/billing/01CBA5-FB0A4C-19F018/reports?organizationId=448885369991&project=recidiviz-123 and filter on the "Cloud SQL" product and break out by SKUs, it looks like the total cost last month was ~$60. Of that, the vast majority was paying for the CPU instance running the DB, followed by network costs. The actual storage costs were essentially negligible. So unless and until our DB grows immensely in size, I don't think the costs associated with keeping more backups (which, because you can't query them, are only storage and no CPU) should be  a concern.

So if we can essentially determine the "perfect world" schedule since the costs are negligible, I'd be in favor of keeping backups for significantly longer. Since we can now do partial restores (as of #1190), we're no longer limited by how many days of data for the entire database we're willing to sacrifice to fix an error. If someone makes a bad change to a scraper and no one looks at that data for 3 months, we could revert just that one region to its earlier state and keep all the rest of the data gathered over that time period.

My personal inclination would be weekly backups, kept for 6 months (in addition to the regular automatic daily backups for the last 7 days).

**Comment by jessex** [comment]
Thanks for the investigation, @zdg2102. Would the weekly backups be incremental like the daily backups, or total?

**Comment by zdg2102** [comment]
If I'm reading https://cloud.google.com/sql/docs/postgres/backup-recovery/backups#about_backup_size correctly, it sounds like all backups are incremental, regardless of if they're automatic or manual

**Comment by jessex** [comment]
@zdg2102 I like your idea of weekly and daily backups. The rolling daily backups give us ability to rapidly, effectively respond to issues in real time, and the longer weekly backups give us the flexibility to deal with long-term or late-discovered issues. Let's use this issue to set up a scheduled programmatic weekly backup saved into the same location as the automatic daily backups.

**Comment by zdg2102** [comment]
Sounds good. I managed to get the curl request set up locally. Once Colin's back, I'll work with him to get it running on app engine :+1:
