### ISSUE TITLE
us_tx_hockley - Entity Matching, matching 1 DB Booking to 2 ingested bookings

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#1129]
https://pantheon.corp.google.com/errors/CPHN66_gi67-Vw?time=PT6H&project=recidiviz-123

**Comment by jamwalla** [comment]
NetData has historical data like:

CHARGE 1 - Admitted 1/1 - Released 1/2
CHARGE 2- Admitted 1/1 - Released 1/1

We can't distinguish between the two bookings.

**Comment by arian487** [comment]
Not happening anymore, closed
