### ISSUE TITLE
Add jurisdiction_id to all people

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#1153]
This is so that we can join our data with the BJS data.

**Comment by rasmi** [comment]
Duplicate of #368.

**Comment by zacharylawrence** [comment]
@rasmi This bug and #368 seem unrelated? I think this might have been mistakenly closed.

**Comment by zacharylawrence** [comment]
Ah, I think you meant #386!

**Comment by rasmi** [comment]
Yes sorry!
