### ISSUE TITLE
Design way to ensure all possible fields are set on each instance of Person, Record, and Snapshot

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#126]
Our hierarchical object model supports the diversity of fields from incoming data streams, but it makes no attempt at validating that all fields that a stream can set are actually being set. This means it is remarkably easy for code for an earlier scraper, for example, to drift as we make changes to the data model. It is not as simple as validating that all fields are set on construction, due to the aforementioned variety. But we do want to know that each ingest integration is setting everything that it can. This could be accomplished through a combination of the to-be-designed validation layer (#44) and unit tests baked into the build.

**Comment by jessex** [comment]
The generic scraper PR (#147) centralized entity creation logic which goes a long way towards solving this problem. However, it could still grow stale if engineers update the fields on core entities without updating the methods on generic scraper.

In this comment thread (https://github.com/Recidiviz/recidiviz-data/pull/147#discussion_r226818174), we discussed creating a lightweight generator that could be run to automatically fill in the required field setters based on what is currently in the entities. However, there is also a need to create a unit test case for generic scraper which explicitly cross-references the list of attributes on the core entities with the list of setters in the generic scraper to ensure that all are included, failing the build if not. We can write this test case independently of the work to create the generator (#153).

**Comment by arian487** [comment]
Obsolete, most of this has been fixed already with the converter/schema work.
