### ISSUE TITLE
Ingest should support ingesting aggregate-level population and admissions statistics

### ISSUE THREAD

**Issue by ghost** [Recidiviz/recidiviz-data#129]
Currently ingestion only supports individual-level data. However many jurisdictions publish reports containing aggregated statistics at a variety of time scales. Ingesting these will greatly increased the breadth and quality of the incarceration data we can provide.

Examples:
Daily KY DOC pop: https://corrections.ky.gov/About/researchandstats/pages/dailycount.aspx)
Weekly KY jail pop:https://corrections.ky.gov/About/researchandstats/pages/weeklyjail.aspx)
Monthly TX jail pop: https://www.tcjs.state.tx.us/docs/AbbreRptCurrent.pdf
Yearly FL DOC pop: http://www.dc.state.fl.us/pub/annual/1617/FDC_AR2016-17.pdf

**Comment by jessex** [comment]
The high-level design question, in the context of our current architecture, is how to fit this into the world of ingest-and-calculate? One could create a scraper for aggregate data, write it to some aggregate-centric modeling within the ingest schema, and then write calculation logic which converts those stored aggregates into fully modeled `*Metric` calculations. One could also smush ingest and calculate together, transforming ingested aggregates into `*Metric` calculations on the fly. The latter seems simpler but we should think about it further to see if there's anything we might miss by skipping the end-to-end pipeline, and how we want to structure this in actual code.

**Comment by arian487** [comment]
Closing in favour of https://github.com/Recidiviz/recidiviz-data/issues/804, nearly done!
