### ISSUE TITLE
Add support for arbitrary query parameters to scraper control requests

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#131]
`scraper_control.py` specifically looks for a few required query parameters, e.g. region and scrape type, for all scraper control requests, i.e. start, stop, and resume. However, some regions may desire arbitrary query params for specific functionality within their scrapers, so `scraper_control` should support passing those parameters into the `scraper.py` interface.

**Comment by arian487** [comment]
Obsolete, not needed as everything is abstracted and child scrapers should never care to do this.
