### ISSUE TITLE
Figure out if the Vermont JailTracker IP blacklisting is jurisdiction-specific 

### ISSUE THREAD

**Issue by ghost** [Recidiviz/recidiviz-data#140]
Running the us_vt scraper in development for a few minutes results in requests that return an error about request frequency. Because JailTracker hosts many jurisdictions, we need to know if this temporary IP blacklisting applies to all jurisdictions hosted on the JailTracker site, or just the jurisdiction that triggered the blacklist. It could also be a session-specific blacklist?

**Comment by ohinds** [comment]
It's not. Seems like we have to limit ourselves to 30 qpm per IP.
