### ISSUE TITLE
Abstract whatever possible from the Vermont scraper into a JailTracker scraper

### ISSUE THREAD

**Issue by ghost** [Recidiviz/recidiviz-data#150]
Vermont is an example of a JailTracker system, but there are [many more](https://www.jailtracker.net/current-facilities). To enable ease of writing scrapers for the other jurisdictions, it would be nice to take advantage of common functionality amongst the JailTracker jurisdictions. 

Some design work will be necessary, as this will add a level of inheritance.

**Comment by ohinds** [comment]
This is no longer relevant. #368 replaces it.
