### ISSUE TITLE
Add test coverage for generic_scraper

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#154]
The new generic_scraper from #147 still needs test coverage. There is an open question as to the best way to test it. It's not reliant on specific website structure so unit testing _should_ be totally sufficient, unlike concrete child scrapers, and the integration of all aspects of the scraper can be tested in the child scrapers.

**Comment by ohinds** [comment]
@arian487 Does the existence of BaseScraperTest make this moot?

**Comment by arian487** [comment]
Mostly, I'd say close this and open another one about expanding the capabilities of the base scraper test.  I'll do that.
