### ISSUE TITLE
Extract more generic parsing/scraping utilities from generic_scraper

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#156]
As discussed here (https://github.com/Recidiviz/recidiviz-data/pull/147/files#r226819044) and here (https://github.com/Recidiviz/recidiviz-data/pull/147#pullrequestreview-166740911), there is more logic related to generalized parsing of information from structured webpages in the generic scraper that can be extracted out into a module like scraper_utils. Such modules will gradually expand over time, so this issue serves to ensure that everything we want to extract out of generic scraper _right now_ has been extracted, not that the class is in a magical "final" state.

One design point: it is likely that this logic would make sense to reside in a standalone library for the open source community, a higher level of abstraction for use by other scraping projects. We don't need to focus on making a neat Python package out of this right now, but consider its vanilla, library-able nature when considering things like class and method names.

**Comment by arian487** [comment]
This is mostly data extractor stuff and the base scraper is substantially changed.  Marking closed.
