### ISSUE TITLE
Decompose scraper_utils

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#157]
As discussed here (https://github.com/Recidiviz/recidiviz-data/pull/147#discussion_r226817845), `scraper_utils` has a variety of functions which do not necessarily belong in the same module, and it is at risk of becoming a difficult-to-read monolith as we add in more logic (as we will do in #156 and other future work). We should decompose it into more targeted modules with collections of related functions. A strawperson proposal for decomposing the module in its current state is included in the linked thread.

**Comment by arian487** [comment]
Most of the logic in scraper_utils is obsolete, some of the stuff makes sense.  This should be a cleanup process instead.  Marking this as medium.
