### ISSUE TITLE
Generalize the handling of arrays and objects in compare_and_set_snapshot

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#159]
As first called out by @ageiduschek and reaffirmed by @arian487, the current logic for `scraper.compare_and_set_snapshot` is a bit brittle in that it special-case handles the `Record.offense` field, looking at the internal fields of any offense in the array (yes, `Record.offense` should be called `Record.offenses`) to see if any of _those_ have changed as part of its logic. However, that logic can be generalized to handle other fields we add in the future which are objects, arrays, or arrays of objects. 

This will make it less brittle, with the goal being that we should not need to update `compare_and_set_snapshot` if and when we update the core entities. It should remain untouched.

**Comment by ohinds** [comment]
Closing this as it's all about old entities. Opened #407 to replace it.
