### ISSUE TITLE
Fix parsing bugs for pa_greene

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#160]
pa_greene currently has some parsing bugs:

- get_offenses fails if no more than one entry exists
- bond and crime_description are not successfully parsed, need to fix the data extraction here
- some fields such as surname and us_pa_greene_id are not scraped properly
- some people fail all data extraction.  For some reason everything is being returned as none, need to investigate further.

**Comment by ohinds** [comment]
Does this still happen?

**Comment by arian487** [comment]
Does not happen.
