### ISSUE TITLE
Handle charge columns more intelligently in Archonix scraper. 

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#172]
Should be done after generic scraper work is complete.

**Comment by terinpw** [comment]
adding a bit more info:

Currently ingest/vendors/archonix/archonix_scraper.py extracts charge info by assuming an ordering to table columns. However the column order is not consistent across all counties using archonix (some counties have extra columns, some fewer, etc), so we need to actually read the table keys when scraping. 

Generic scraper work should handle this easily, so let's wait until that's in.

**Comment by arian487** [comment]
Unecessary thanks to data extractor.
