### ISSUE TITLE
Data extractor: search for keys outside table cells

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#181]
the DataExtractor class should manually search for keys in other elements besides table cells. Common patterns include:
- [x] `<span>Key: Value</span>`
- [x] `<label>Key</label><span>Value</span>`
- [x] `<span><label>Key</label>Value</span>`

and there are probably many others.

**Comment by jamwalla** [comment]
Since DataExtractor works over table cells, this should be solved by preprocessing unstructured fields and converting them to table cells.

**Comment by rasmi** [comment]
(sorry to revive, but I didn't know you could tick the checkboxes in issues and have it show progress completion as a result -- pretty neat!)
