### ISSUE TITLE
Upgrade pylint when new release fixes decorator false positive

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#193]
[As discussed in this Pylint issue](https://github.com/PyCQA/pylint/issues/259#issuecomment-267671718), Pylint can generate false-positives when making calls to functions decorated in certain ways. This is happening in a sqlalchemy `insert` call in `sql_database`: `E: 41,27: No value for argument 'dml' in method call (no-value-for-parameter)` though `dml` is not an actual argument for us to pass into `PEOPLE.insert()`. 

For now we will do inline pylint disables on insert calls, but as soon as a Pylint release fixes this we should upgrade.

**Comment by zacharylawrence** [comment]
#197 makes this issues obsolete but should probably still be fixed when possible.
