### ISSUE TITLE
Decide how to handle unstructured names

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#206]
Right now ingest info takes two name fields, `given_names` and `surname`. Some websites simply have a name field that isn't broken down into parts. We should decide on either a uniform scheme for parsing this (something simple but consistent, or something more complex like `nameparser` that @arian487 mentioned) or decide not to parse it and store the raw string provided (re: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/).

This has some implications on entity matching and depends on the name storage discussion.

**Comment by jessex** [comment]
That's a great article, @colincadams. Thanks for sharing.

**Comment by arian487** [comment]
I actually think we should make it even easier on the person and just concatenate the given_names and surname we get from the ingest_info, throw it in the name parser, and then use whatever is spat out.  Having only a fullname field can be annoying if the site breaks it down (data extractor can't concatenate fields).  By letting them do whatever they want with the name fields, and letting us throw it into the nameparser it'll be consistent and shoud just cleanly work.

**Comment by arian487** [comment]
Fixed in https://github.com/Recidiviz/recidiviz-data/pull/611
