### ISSUE TITLE
define enum values for database fields

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#215]
The following fields need to have enums defined:
 - `person.race`
 - `person.ethnicity`
 - `booking.release_reason`
 - `booking.custody_status`
 - `booking.classification`
 - `charge.offense_code` (`charge.statute` -> BJS code)
 - `charge.degree`
 - `charge.charge_class`
 - `charge.status`
 - `charge.court_type`
 - `bond.type`
 - `bond.status`

In addition, as we write these enums we'll also want conversions from common ways of expressing these values (i.e. 'caucasian' -> 'white')

**Comment by jamwalla** [comment]
@ohinds-vera - I started writing some of this in #212, but I wouldn't want to write too much without seeing the data on a lot of different pages. Any thoughts on how we should go forward here?

**Comment by zdg2102** [comment]
Enums are now defined for both application and database layers.
