### ISSUE TITLE
There should be a ChargeLevel class in the recidiviz.common.constants.charge module

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#333]
... and associated constants

**Comment by ohinds** [comment]
When this issue is closed, us_ny_scraper should be modified to use this class.

**Comment by zdg2102** [comment]
"Level" is currently a String field on Charge in the schema. Does it need to be an enum instead?

**Comment by ohinds** [comment]
Were going with the idea that we don't need to handle this as an enum, due to variability in what this even means between jurisdictions.
