### ISSUE TITLE
Determine which fields on charge, bond, sentence are needed for entity matching

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#350]

**Comment by jamwalla** [comment]
Mostly we'll close the old entity and create a new one if anything is different. @ohinds is going to run through the schema and see if there's anything we expect to change regularly (e.g. maybe charge fees get added or bumped up).

**Comment by ohinds** [comment]
Charge:
next_court_date and judge_name

Bond:
status

I'm in the process of adding 'Incarceration' and 'CommunitySupervision' entities. If those make it through, this will be relevant:

Incarceration:
release_date

CommunitySupervision:
release_date
agency
officer

**Comment by jamwalla** [comment]
@ohinds thanks!! Should Hold.status change?

**Comment by arian487** [comment]
I believe this is done correct?

**Comment by jamwalla** [comment]
yes! We'll have to look over our database and see if anything is causing us to drop entities to frequently, but we have a working version of this in the code.
