### ISSUE TITLE
Determine how to match people with incomplete birthdate information

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#351]
Currently we only match a person if full birthdates + full names are provided. 

Do we want to match in any of the following cases?
- Inferred birthdates + full names
    - if we do this case -- what do we do when a person ages (their inferred birthdate changes).
- No birthdates + full names

**Comment by jessex** [comment]
>what do we do when a person ages (their inferred birthdate changes)

Just to make sure I understand the implementation:

- If we first see their booking in November 2018 and their age is, say, 30, then we'll infer a birthdate of January 1, 1988?
- And if we scrape that same booking a couple of weeks later in December 2018 and the ingested age is now 31, then we'll infer a new birthdate of January 1, 1987 and update that on the "master" table while an older history record will still have the previous inferred birthdate?
- And if we scrape that same booking a month later in January 2019 and the age is still 31, will we infer a new birthdate of January 1, 1988?

**Comment by ohinds** [comment]
I think we should match on inferred birthdate, we just need to be careful about how we do that. I think there has to be special case logic in the entity matching system that accounts for the situations @jessex outlines above. So, for example, we allow the birth_date to be off by exactly one year if it's inferred and still indicate a positive match. The birth_date should then be updated in the person entity. I *think* this handles all cases?

**Comment by jessex** [comment]
I think that would handle all of the cases I mentioned, at the expense of potential false positives. But to make sure I understand, the false positive would be that two people have the same full name _and_ birthdates on the same day that are in consecutive years. Is that right? If so, that's probably rare enough to be acceptable.

**Comment by jamwalla** [comment]
@jessex, I think the false positive you're describing is only a problem for birthdates inferred from age. In that case we'll say that their birthdate is Jan. 1 of the year we think they were born. Since the page probably lists ages for everyone, we'll have more collisions, but for a lot of regions it's still probably acceptable.

**Comment by jamwalla** [comment]
I reopened this bug so we can think about doing entity matching for websites that only list names, i.e. match despite the absence of birthdates. For many small jails this seems worth doing, but if there are large systems with sparse data we'll probably end up with too many collisions.

**Comment by jessex** [comment]
Right. So the false positive case is that two people have the same full name and the same age (+ or - 1 year) at the time of scrape, and both have active bookings, and the source data has no external ids and only includes age so we infer birthdates for both individuals?

**Comment by terinpw** [comment]
Yup @jessex, that's correct!
