### ISSUE TITLE
Create playbook for catastrophic errors 

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#355]
We have a few errors that stop the normal workflow of our scrapers, we should have documentation on what they are and what manual work is necessary to fix. 

* EntityMatchingError - in entity_matching.py (when multiple ingested people or bookings are matched to the same db person/booking)

**Comment by ohinds** [comment]
We need an enumeration of what all the catastrophic failures could be.

**Comment by zacharylawrence** [comment]
Potential implementations:

1. Abort the entire scrape session if any failure is encountered during a scrape (eg. Can't parse enum, can't parse HTML, etc.). This requires storing the entire scraped data into a temporary location until ready to commit to the database.
1. Write all data to the database, dropping only rows that failed to scrape successfully. This leaves us open to potentially biased data. For example, if we failed to scrape all people of a specific demographic class, then the resulting data written to the database would be biased.
1. Write all data to the database, dropping only rows that failed to scrape successfully. Additionally write to a tabled keyed by <Region, ScrapeTime> that points to a boolean if the scrape session was successful. This would allow you to join against this table if you wanted only "fully scraped" data.

**Comment by arian487** [comment]
I'm definitely against 1.  I'd have to think about 3 but where I land is some hybrid of 2 and 1.  For some class of failures I think we should invalidate the whole scrape, and for other classes we should be ok just dropping rows. 

For example, if we are worrying about biasing, maybe if there are enum errors in race, ethnicity, or gender, we should fail everything but for example if someone accidentally mispells a felony class for a single record, that should not invalidate the whole scrape.

**Comment by arian487** [comment]
I'm going to write up a mini proposal for early next week, but this won't happen for drop day.  It is definitely important to think about this sooner rather than later, but I'm going to remove it from drop day, its not a hard blocker.

**Comment by arian487** [comment]
I'm going to close this for now since the playbook has been created and agreed upon.
