### ISSUE TITLE
Consider how to handle invalid values provided in ingest_info fields that are turned into enum values

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#361]
Currently, the best way to check in `populate_data()` whether a string to be inserted into and `ingest_info` fields will map to a valid enum value is to call the `from_str()` method on the enum passing the string value, just for the side effect of it throwing a KeyError if the string isn't found. This isn't a particularly pleasing way to test validity. 

Consider adding a `check_valid()` function, or just returning None as alternatives. Each have downsides.

**Comment by arian487** [comment]
This is now fixed with: https://github.com/Recidiviz/recidiviz-data/pull/525
