### ISSUE TITLE
Convert ingest info _Charge.number_of_counts into multiple entity charges

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#371]
currently ingest_info._Charge has field number_of_counts, and the entity/schema versions of charge do not (the assumption was that we would create separate charges for each count).

**Comment by ohinds** [comment]
Update this google doc that references this issue when it's closed:

https://docs.google.com/document/d/16j-Ng8c4MGyKArDrTsyLjQ-MQfYbxTsoWWmZBBLG0iA/edit#
