### ISSUE TITLE
Assess costs/benefits of halting system to do migrations

### ISSUE THREAD

**Issue by zdg2102** [Recidiviz/recidiviz-data#393]
- Lets us avoid having to keep the prod release and the database in sync across multiple releases
- Assumes that our scraper tasks are stateless
- Might have ramifications on direct ingest (if uploaders assume the system is always available)

**Comment by ohinds** [comment]
It's also unclear if the direct ingest partners will try to directly interface with our system, or whether they will just drop data in a staging area, allowing us to ingest it when the migration is complete.

**Comment by jessex** [comment]
I think to evaluate this better, I'd need to know what "system" refers to here. Is it only the GAE application that lives in recidiviz-data, i.e. the scraping pipeline and the ingest API? Is there any benefit to separating those two and halting only the former while letting the latter stay live? 

>It's also unclear if the direct ingest partners will try to directly interface with our system, or whether they will just drop data in a staging area, allowing us to ingest it when the migration is complete.

It's unclear now for a small set of clients, but an expanded set of clients in the future makes it increasingly likely that we'll eventually want to ensure we don't have to explicitly schedule and manage migration windows with government entities. I can say from experience that those processes are fairly nightmarish.

**Comment by zdg2102** [comment]
The explanation of the process for how the releases and migrations need to be timed with each other is now added to the README with #1303
