### ISSUE TITLE
us_fl_martin_county sometimes infers everyone as released.

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#399]
Not sure why but one of the days every single person was inferred release in martin county.  Entity matching 'should' be working for this region.

**Comment by HalfdanJ** [comment]
Would be handy if there was a way to grab a snapshot of the data that is processed that then can be used to debug a scraper (in the cases where it's a specific scraper implementation issue). That could also be useful for development, where I as a Dev can run something that grabs a snapshot that I then use offline to test and develop the scraper. 

To help with this specific issue it would of course need an historic archive which might not be feasible. But it would give me as a developer of a scraper a tool to learn how the site can change over time, and find edge cases.

**Comment by jessex** [comment]
It is possible to set an environment variable, `PERSIST_LOCALLY`, which will let you write into Sqlite locally. Would that be helpful for what you have in mind?

**Comment by HalfdanJ** [comment]
Moved my feature request to #433

**Comment by jessex** [comment]
Ah I see I misunderstood your goal here. Thanks for the issue, @HalfdanJ!

**Comment by arian487** [comment]
This is fixed now that we are no longer storing generated external ids in the database: https://github.com/Recidiviz/recidiviz-data/pull/516
