### ISSUE TITLE
Remove the sleep in scraper control

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#401]
Not sure why we need a sleep, but it is annoying.

**Comment by ohinds** [comment]
@jessex, is there any reason to keep this around?

**Comment by jessex** [comment]
I believe the sleep was originally added because it was believed that the `put()` call wasn't flushed from cache to Datastore and that the first task might get queued up and run, updating the wrong session. If we believe this is not possible, we can remove those sleeps.

**Comment by arian487** [comment]
This was removed in the python 3 merge!
