### ISSUE TITLE
Handle if a string is very long in the database

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#409]
Right now, some fields might have very long descriptions, like charge.name.  If its too long the persist fails with: 'DataError: (pymysql.err.DataError) (1406, u"Data too long for column 'name'.  We should decide how to handle this.

**Comment by rasmi** [comment]
This seems [MySQL-specific](https://stackoverflow.com/questions/18897420/data-too-long-for-column-why). For PostgreSQL, we can use the [`text`](https://www.postgresql.org/docs/9.0/datatype-character.html) type ("variable unlimited length") or manually set a max length with the `character varying(n)` type. Postgres's `text` type isn't in the SQL standard, but it should work fine for our purposes.

**Comment by rasmi** [comment]
SQLite's text type has a [10^9 byte limit](https://www.sqlite.org/limits.html), so we should be safe there too. If we want to stick to MySQL, we can manually specify a large number for the string length, but the plan was to just use Postgres from the start (the MySQL db was temporarily spun up because our libraries didn't allow us to call Postgres from Python 2 -- @zdg2102 ).

**Comment by jessex** [comment]
I'm happy to go all Postgres all environments!

**Comment by rasmi** [comment]
We should still use SQLite for local development, Postgres is just for the production database. Because we're using SQLAlchemy, the backend is abstracted away (except in cases of database-specific errors like this one).

**Comment by zdg2102** [comment]
This isn't a MySQL issue, this is an issue with the SQLAlchemy schema declaration. I set all the string columns to String(255). I'll update Charge.name to Text, and that should resolve the issue for all 3 database types (Postgres/MySQL/SQLite)

**Comment by rasmi** [comment]
Got it! I incorrectly assumed that we were just declaring some generic string type that SQLAlchemy was mapping to a limited-length string in MySQL. Good to know this was done explicitly rather than accidentally. Thanks Zach!

**Comment by zdg2102** [comment]
No problem!

**Comment by zdg2102** [comment]
Resolved with #504
