### ISSUE TITLE
`place_of_residence` should be replaced with `county_of_residence`, or just `from_this_county`

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#415]
In the interest of not storing PII, I don't see much reason to store someone's address. What we are really interested in is whether someone is being held somewhere other than where they live. I might be talked out of even having this information at all, too.

**Comment by jessex** [comment]
>What we are really interested in is whether someone is being held somewhere other than where they live.

Can we say this for certain? We have no interest in understanding the incarceration rates or any other metrics by county of residence?

**Comment by ohinds** [comment]
> > What we are really interested in is whether someone is being held somewhere other than where they live.
> 
> Can we say this for certain? We have no interest in understanding the incarceration rates or any other metrics by county of residence?

We do have interest in that analysis, but we made a call here to minimize the PII for now. Also, the reliability of the address data is unknown and likely highly variable. 

For now, fixed by #1231
