### ISSUE TITLE
'county_of_commitment' in sentence should be changed to 'place of conviction'

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#419]
So we can accommodate jurisdictions that aren't county-level, like the feds.

**Comment by jessex** [comment]
Well let's be precise here. We have a field that talks about where someone was _committed_ to incarceration, and the current title of this issue suggests renaming it to be about where someone was _convicted_. The previous comment from @zdg2102 suggests renaming it to be about either where a person was _sentenced to go_ (e.g. "you're going to Yonkers") or where the _sentencing actually occurred_ (e.g. they were sentenced in the Yonkers City Court 9th District)--it's a bit ambiguous but either way it's about sentencing. So now we have 3 name possibilities and they all refer to different aspects of the criminal justice pipeline.

So what are we actually concerned with tracking in this field, and do we need multiple such fields?
