### ISSUE TITLE
Reduce the size of the repository, targeting /libs

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#45]
[Apparently](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27), [nearly all](https://cloud.google.com/appengine/docs/standard/python/tools/built-in-libraries-27) third-party Python libraries need to be manually included inside of the `/libs` directory of a GAE Python app. Particularly after the introduction of MapReduce via pull request #29, the `/libs` directory is much, much larger than our own work in `recidiviz-data`. 

Ideally, we would not need to do this and would be able to deploy to GAE without carrying around these `/libs`. One route would be to customize our deployed environment [with GAE-flexible](https://cloud.google.com/appengine/docs/flexible/) via Docker.

**Comment by jessex** [comment]
#38 is trivial to set up with our current environment (which you will see soon), but your point stands! Most or all of operational issues would be easier with a more flexible // containerized environment. It's definitely in our future, just a matter of prioritization.

**Comment by jessex** [comment]
As part of #69, we introduced an unofficial `appengine-sdk` dependency (there's no official one from Google) through pip to make testing on Travis CI easy, instead of, say, downloading Google Cloud SDK libraries and unzipping them and wiring them up correctly with bash scripts inside of `.travis.yml`. It is worth looking into whether or not this SDK would allow us to remove the GAE-specific cruft from `/lib`, but I doubt it.

**Comment by jessex** [comment]
I was talking through this with @jbrambleDC today and we more or less came to the same conclusion on this one, which is similar to @eshilts' proposal above: migrate ingest into the Docker-powered [App Engine Flexible environment](https://cloud.google.com/appengine/docs/flexible/) (which is a more managed take on GCP's Compute Engine) as opposed to jumping full blown into GCP Kubernetes Engine or raw Compute Engine. Here are [more docs](https://cloud.google.com/appengine/docs/the-appengine-environments) on App Engine environment comparison.

This would be a cheaper migration that allow us to continue to leverage all of the task queue code and infrastructure that has proven so valuable, while killing off the `/lib` directory through our custom images. 

One question here is whether GAE MapReduce, the current basis of our calculation pipeline, would migrate as cleanly. I suspect it would be fine, but a remedying option would be to go ahead and migrate calculation to Cloud Dataflow, which is something we should be considering anyway, for the purposes of long-term scale. That would break calculation out of the artifact and provide a cleaner separation between the two halves of our data platform.

I know @matthewroot has expressed some skepticism about GAE early on, so curious to hear his thoughts on this. I've been a big fan of it so far and the task queue functionality is superb, in my opinion.

**Comment by colincadams** [comment]
🎉
