### ISSUE TITLE
Tasks are not running concurrently

### ISSUE THREAD

**Issue by rasmi** [Recidiviz/recidiviz-data#459]
Only one task is running at a time due to the `bucket_size` [parameter](https://cloud.google.com/appengine/docs/standard/python/config/queueref#syntax) being set to 1 for all queues in `queue.yaml`.

**Comment by rasmi** [comment]
After setting `bucket` and `max_concurrent_requests` to their max values (#460 and #462, respectively), `rate` is now the limiting factor on concurrent requests.

**Comment by jessex** [comment]
Great find, @rasmi.

**Comment by rasmi** [comment]
Bug cred to @arian487!
