### ISSUE TITLE
Encoding issue in us_ny

### ISSUE THREAD

**Issue by rasmi** [Recidiviz/recidiviz-data#461]
Inspection of the `Charge` table shows some charges that are formatted as:

```
DUI (BAC .10 - Â€¹ .16; SECOND OFFENSE)
```
Searching that series of symbols leads to [this helpful page](https://www.i18nqa.com/debug/utf8-debug.html) that indicates the page may be returning the `‹` symbol. In Python:
```
>>> '‹'.encode('utf-8').decode('windows-1252')
'â€¹'
>>> 'â€¹'.encode('windows-1252').decode('utf-8')
'‹'
```
However, trying to encode/decode the whole string gives an error. I'm not sure how careful we want to be about UTF-8 encoding everything -- ideally we are consistent everywhere, but I can see situations like this one where the logic necessary to parse/handle malformed text could get ugly.

We could use something like [`chardet`](https://chardet.readthedocs.io/en/latest/usage.html) to detect encodings in such situations, though I doubt they will change within a single site.

**Comment by colincadams** [comment]
stolen
