### ISSUE TITLE
'NO RECORDS FOUND.' in charges for us_pa_greene

### ISSUE THREAD

**Issue by rasmi** [Recidiviz/recidiviz-data#463]
In `us_pa_green` charges, some statutes are empty, but others list the string `NO RECORDS FOUND.`.

**Comment by arian487** [comment]
Closing this in favour of https://github.com/Recidiviz/recidiviz-data/issues/480

It creates empty objects, that being said 'no records found' is a valid thing because its scraped from the website.

**Comment by rasmi** [comment]
To clarify, on a charges table that looks like this:
<img width="608" alt="screen shot 2019-01-04 at 2 40 03 pm" src="https://user-images.githubusercontent.com/2267370/50707387-a9833880-102e-11e9-93d7-78b718afc8df.png">
A charge object is being created and 'NO RECORDS FOUND.' is being set as the `statute` of that charge. This seems like incorrect behavior because it complicates things like counting the number of charges a person has. I think no charge should be created when a table like the above is encountered, and if we want to separately store information about the facility not knowing the charges, that can perhaps be done on a booking level, but it may be unnecessary.
