### ISSUE TITLE
us_ar_van_buren charges are not split

### ISSUE THREAD

**Issue by rasmi** [Recidiviz/recidiviz-data#464]
It seems that multiple charges in `us_ar_van_buren` are being coupled into a single Charge object, for example:
```
TERRORIST THREAT 1STTHREATEN PHYS INJHARASSING COMMUNICATIONSPHONETERRORIST THREAT 1STTHREATEN PHYS INJBATTERY 3RD DOMCAUSES SERIOUS INJURYCRIMINAL MISCHIEF2NDPURP TAMPERS
```

**Comment by arian487** [comment]
This is a brooks jeffery vendor issue, closing in favour of: https://github.com/Recidiviz/recidiviz-data/issues/465
