### ISSUE TITLE
Improve validation errors

### ISSUE THREAD

**Issue by HalfdanJ** [Recidiviz/recidiviz-data#475]
When a validation error happens in the `base_scraper_test` (through `validate_and_return_populate_data`), it currently doesnt give a lot of hints at what is wrong. All I see is

```
        if errors:
>           raise ValidationError(errors)
E           recidiviz.persistence.validator.ValidationError

recidiviz/persistence/validator.py:48: ValidationError
```

It seems in source that the error does contain more information, might just be a matter of adding some error logging in `base_scraper_test`?

**Comment by jessex** [comment]
Better logging would help, but I believe that some of the Stackdriver tools automatically extract error/exception messages and surface them in various ways, so we should make sure anything we raise has an appropriate message included.

**Comment by jamwalla** [comment]
I believe the errors raised in the converter are clearer now, ie only `EnumParsingError` and `ValueError`. I'm going to close this but reopen if I'm mistaken!
See #1094
