### ISSUE TITLE
DataExtractor not finding multi_key_mappings in <li> objects 

### ISSUE THREAD

**Issue by HalfdanJ** [Recidiviz/recidiviz-data#479]
Coming up as issue in #329. 

I have following html 

```
<li class="BookingDate">
<label>Booking Date</label>
<span>1/1/2017 11:41 AM</span>
</li>
```
that is repeated multiple times as multiple bookings. So adding

```
multi_key_mapping:
  Booking Date: booking.admission_date
  ...
```

But this is never found. Did a little bit of debugging, and the [code in DataExtractor](https://github.com/Recidiviz/recidiviz-data/blob/2d6a5df3f42659edf52a4d6595aa0efd5349eebb/recidiviz/ingest/extractor/data_extractor.py#L248) that finds elements that arent `<td>` or `<tr>` only gets called on `key_mappings`, not on `multi_key_mappings`

**Comment by jamwalla** [comment]
We definitely need to work on the documentation. In this case, Booking information should be in `key_mappings`, not `multi_key_mappings`. `multi_key_mappings` is really only meant for table columns where we build an object along a row. In this case, we scrape all of the first booking's information and create a new booking when we see the booking keys again. I added some pruning functionality, so let me know if you can get this to work with `key_mappings` for booking data instead.

**Comment by HalfdanJ** [comment]
Aaah that makes sense
