### ISSUE TITLE
IngestInfo deepdiff doesnt work on None objects

### ISSUE THREAD

**Issue by HalfdanJ** [Recidiviz/recidiviz-data#481]
The new DeepDiff 🎉#458 doesnt work if the actual value is None: 

```

    def __eq__(self, other):
>       return self.__dict__ == other.__dict__
E       AttributeError: 'NoneType' object has no attribute '__dict__'
```

since `other` is None. I tried adding `if not other: return False`, in all the `__eq__`, and that gives a nice output, but not sure thats the right place to solve it.

**Comment by jamwalla** [comment]
Yes, we should definitely do that! If you have that code up we can make a quick PR, if not I can make one.
