### ISSUE TITLE
Investigate record scrape failure of DIN 80A4470

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#49]
The scraper failed to scrape Record details for DIN #80A4470, and as a result failed to prevent duplication on subsequent re-scrapes of the inmate (see Cloud Console > Datastore > Entities > Query by kind > Select 'Record' entity > Sort by 'custody_date').

Investigate cause of Record scrape failure.

Also, double-check the following other DINs which have no Custody Date:
- 58A0017
- 77A3499
- 82B0712
- 77B2041
- 82A0353
- 73B5612
- 81A3539

**Comment by ohinds** [comment]
Fixed by #422
