### ISSUE TITLE
Investigate records marked as being out of custody without a release date

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#51]
As noted in #47, there is an issue wherein some very small number of records in Datastore are marked as being out of custody but have a `last_release_date` of null. This was leading to a runtime error before we applied a workaround in calculation. However, we should understand if this is an issue in the DOCCS source data or a bug in ingest.

Impacted records can be found with a query where `is_release = true` and `last_release_date = null`. The variety of shapes of data that match this case seem to indicate it is a data bug.

**Comment by cawarren** [comment]
These appear to be source data bugs. Checked a couple of DINs (15B1325, 77B1333) - the inmates are recorded as released, but no date or reason for release is provided.

**Comment by jessex** [comment]
I figured as much. Thanks. We already have a workaround in place, but I think there is a need to define more formal data validation in ingest and calculation. I just commented to that effect on #44. Going to close this one out as FIXED by #47.
