### ISSUE TITLE
Consider better queue params

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#510]
Its unclear what a good set of params to use is.  As is, it looks like it might be doing too many requests at once.  Need to investigate a better number.

**Comment by colincadams** [comment]
Clarification: This refers to parameters tuning queue behavior defined in `queue.yaml` like `bucket_size` or `max_concurrent_requests` correct? As opposed to the params that we put into a queue message / request?

**Comment by arian487** [comment]
Closing this for now, as the queue params are now much smaller and performing better.
@colincadams you're correct
