### ISSUE TITLE
handle BondType and BondStatus in converter when bond is 0 / 'no bond'

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#532]
NO_BOND could mean 'no bond possible' (you can't be bonded out, bond amount = ∞). Or it could mean 'no bond required' (you're released on recognizance, the corresponding charge was dropped, etc.). We should split up NO_BOND into these categories, NO_BOND_POSSIBLE and NO_BOND_REQUIRED.

This came up in #329; after we make this change we should map `ROR` and `DROP NOTICE` to `NO_BOND_REQUIRED`.

cc @ohinds

**Comment by zdg2102** [comment]
"No bond possible": BondType.NO_BOND, BondStatus.DENIED
"No bond required": BondType.NO_BOND, BondStatus.NOT_REQUIRED

I'm about to add the new BondStatus values for #491, so I think the work required from this issue will be to ensure the converter handles them appropriately

**Comment by arian487** [comment]
This has bveen fixed across a few PRs from a long time ago.
