### ISSUE TITLE
There should be an `admission_reason` field in booking

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#536]
Let's start with an enum with values:

From Escape
New Commitment
Parole Violation
Probation Violation
Transfer

**Comment by jessex** [comment]
@ohinds, would you suggest inferring admission reasons in any cases, or leaving them as None when not explicitly provided?

**Comment by ohinds** [comment]
I think leave them as None when we don't have other info.

**Comment by terinpw** [comment]
When we infer release we set the release_reason to `INFERRED_RELEASE`. Shouldn't we keep admission_reason and release_reason in sync with regards to how we treat inferred information?
