### ISSUE TITLE
Scraper generalization (high-level notes / needs)

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#55]
Generalize the current ingest pipeline to accommodate several additional types:
- A daily roster-style system (county-level)
- A prison system without historical information
- A prison system that requires specific name searches / doesn't handle fuzzy-matching

Generalization work will include:
- Creation of per-region config files
- Extraction of Scraper class with required methods
- Extraction of docket and session functionality

...and much more. Filing this as a place to keep notes, as this will be the next large PR on the Ingest side after snapshot scraping.

**Comment by jessex** [comment]
Another technical point: we should likely be making use of Python Abstract Base Classes here. Check out the [PEP](https://www.python.org/dev/peps/pep-3119/) and the [module docs](https://docs.python.org/2/library/abc.html). I could see an interface around individual region scrapers to the effect of start, stop, and resume commands, and/or more fine-grained interfacing around navigation and parse functionality. We'll need to feel it out, but having a discrete "interface" for region scrapers to extend will provide much more in the way of structure and safety than our introspection-based model we have right now.

**Comment by cawarren** [comment]
I've added all of the work issues in the ingest design doc, and created a tracking issue (issue #90)

Up to you if you'd like to keep this general issue open. I've included your last comment (re: abstract scraper) in the issue to pull out scraper logic (issue #87).

**Comment by jessex** [comment]
I think we've got everything adequately covered. Let's close this one out with a reference to it from #90.
