### ISSUE TITLE
Scraper docs rewrite

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#56]
The ingest pipeline needs a documentation pass to illustrate general functionality as well as needs for supporting a new region.

Placeholder issue for notes about the work, coming post-generalization.

**Comment by jessex** [comment]
As part of this, let's make sure we have super clear documentation on how to integrate another region, including general concepts such as the decision reached in #97, that each task should perform one request against the source system.

**Comment by arian487** [comment]
Obsolete
