### ISSUE TITLE
Sentence should be able to handle a date as min and max length

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#567]
Right now it expects a number of days, but perhaps we should be storing a date for that field?

**Comment by jessex** [comment]
From what I understand, sentences in many (most?) jurisdictions will be a set of possible dates based upon a prescribed sentence length. So your sentence will be, say, X months, and that represents the maximum amount of time you could stay. From that, you'll have, say, 4 dates calculated: max release date, "good time" release date (a min release date if you behave as desired), possible parole date (which could change over time if parole is denied, for example), and a sort of slack/override date that could represent a variety of jurisdictional things designed to incentivize you to behave certain ways by letting you out early.

I'd be curious if @ohinds thinks that this holds true in jails as it often does in prisons, and whether it's something we should consider here. But I think sentence length and an array of real or proposed release dates seems like a good schematic choice to me.

**Comment by jessex** [comment]
I'm going to close this one. In the new incarceration entity that's being worked on, there will be sentence length day fields and there will be fields like projected release date and parole eligibility date. Best of both worlds.
