### ISSUE TITLE
decide on a process for orphaned entities

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#573]
If we drop entities besides those attached to a booking, nothing in the database will point to them. We could run a clean up job, or we could have bookings point to them as well. cc @zdg2102

**Comment by zdg2102** [comment]
`booking_id` has been added to `Bond`/`BondHistory` and `Sentence`/`SentenceHistory`.

Reassigning to @terinpw to ensure any entities orphaned during entity matching still get merged back into the session so their changes aren't dropped
