### ISSUE TITLE
add INFERRED_DROP to droppable fields

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#585]
@zdg2102 @terinpw once we make all the decisions about #573, we will probably want a way of distinguishing between objects whose 'dropped' status was scraped vs. inferred

**Comment by terinpw** [comment]
For Booking we've already determined we do the following when a booking doesn't show up on a scrape. 
```
release_reason: INFERRED_RELEASE
release_date: date of last scrape
release_date_inferred: True 
```

But what field/fields should we do for: Hold, Arrest, Charge, Sentence, Bond

**Comment by ohinds** [comment]
I think just leave all the fields in hold, arrest, charge, and sentence the way they were. We have no further information, so just leave it?

**Comment by jamwalla** [comment]
To be clear, we're talking about what an inferred drop would look like for each of those objects. E.g. if there are fewer charges on a subsequent scrape, do we change the charge status? mark the charge as 'drop_inferred'? etc.

**Comment by terinpw** [comment]
Chatted with Oliver offline and to recap our conversation his points were:

When a booking is resolved:
- We only mark the booking INFERRED_RELEASE (nothing happens to the children beneath it b/c we can't assume anything about Charges/Holds/Bonds/ or Sentences)

When an entity is removed from a booking in successive scrapes we should update following fields on the entities:

Charge: status changes to `INFERRED_DROPPED`
Hold: status changes to `INFERRED_DROP`
Bond: status changes to `UNKNOWN_REMOVED_FROM_SOURCE`
Sentences: status changes to `UNKNOWN_REMOVED_FROM_SOURCE`

**Comment by jamwalla** [comment]
cc @zdg2102
