### ISSUE TITLE
Regions should have a way of telling Infer release not to release

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#598]
Some websites you can only query people booked over a time period (one month for example) so infer release would mark them released if they are there for more than one month.  Regions need a way of telling the releaser to mark them in a different state (MISSING_FROM_SITE for example) if missing does not necessarily mean release.

Snapshot scraping would need to be prioritized for these states.

**Comment by terinpw** [comment]
Closed by #639
