### ISSUE TITLE
consider bucketizing birthdates

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#621]
To increase anonymization, we should reduce the granularity of birthdates after people are released. For example, we can scrub the day/month of birthdates and still have accurate ages; if two-year or larger buckets are acceptable we should do that. Depending on what we think about #600 we might want a bucket for all juveniles?

**Comment by arian487** [comment]
Fixed in https://github.com/Recidiviz/recidiviz-data/pull/1170
