### ISSUE TITLE
never store names/birthdates if external ids are provided

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#622]
Since we use external ids as a source of truth for entity matching, we should never store people's names and birthdates if we can match on person ids.

**Comment by jessex** [comment]
A general comment on issues like this one and #621: I would like us to consider strategy interfaces for questions such as under what conditions sensitive fields or PII are stored. For example, much of this ingest code and schema can be reused in contexts where fields will be stored under different circumstances or for different lengths of time, and it would be great if this kind of logic was pluggable from the start.
