### ISSUE TITLE
Migrate any non-NY-specific fields to top-level models

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#63]
Our approach to date has been to put very common fields into top-level models (`Record`, `Inmate`, and `Snapshot`), and fields that are less common / seem specific to New York to the region-specific subclasses.

Instead, we should have any field that is not explicitly region-specific be placed in the top-level model and left as null for regions which don't provide it.

Fields to migrate from `UsNyRecord` and `UsNySnapshot` to `Record` and `Snapshot`:
```
    last_custody_date
    admission_type
    county_of_commit
    custody_status
    earliest_release_date
    earliest_release_type
    parole_hearing_date
    parole_hearing_type
    parole_elig_date
    cond_release_date
    max_expir_date
    max_expir_date_parole
    max_expir_date_superv
    parole_discharge_date
```

In the future, only truly state-specific fields should live in the region-specific subclasses for these models.

**Comment by cawarren** [comment]
_This is part of ingest generalization work_

The task described above is still the core chunk of work, but there's a few pieces of cleanup that need to go with it. Adding them below as part of the same enhancement.

Scope update:
- Add `region` field to `Record` model (as it is in `Inmate`)
- Add `id_is_fuzzy` field to `Record` model (as it is in `Inmate`)
- Update scraper to construct `Record` and `Inmate` entity keys when persisting to datastore from `region_code` + `(inmate/record)_id`, not just `(inmate/record)_id` as it does now (since record or person IDs may clash across states or jails). This may require an additional migration for the current datastore.

**Comment by cawarren** [comment]
## Status update
I've set up a _recidiviz-staging_ instance in Google Cloud Platform, imported the last backup of our prod datastore, and tested both `Record` and `Snapshot` migrations as implemented in PR #46.

Small sample size test migrations have run as expected, with no additional changes / fixes needed. To minimize infra costs, I'm going to add additional changes for this issue before running a full-scale test migration on staging, which will then (if successful) lead to the full migration on our prod datastore. 

To make changes from this issue / finalize staging of migration work, we need to decide on how to work around the PolyModel issue that prompted this change (the issue itself is how we're fixing it moving forward - in this case, we need to decide how to work around it during the migration). 

A brief write-up on the issue, approaches we can take for it, and a recommendation for go-forward are below.

## Decision / discussion

**Migration challenge**
The migration path would be straightforward if Record were a new model, rather than the existing parent class of UsNyRecord. Because they're both part of the same PolyModel, migrating fields _upward_ is challenging, since Cloud Datastore will reject adding the properties to `Record` with the same names as properties in the descendant `UsNyRecord` - they're both stored in the same Datastore table, so multiple columns with the same name in that table is no bueno.

Snapshots are simpler, because they _are_ a new model - the prior model was `InmateFacilitySnapshot`. As a result, duplicate properties between different levels of PolyModel aren't an issue on the `Snapshot` side of the migration.

This challenge with vertical PolyModel property migration is part of the motivation for this migration in the first place - because they're going to be a pain to migrate to superclasses in the future, it's best we just keep anything that might be general there at the start. As a result, once we have this issue resolved we shouldn't hit this problem moving forward.

**Approaches**
*Approach 1: Rename `Record`*
The easiest solution is to rename the `Record` model. It's not a perfect name for what it describes, and doing so would get us out of the PolyModel stickiness. We can create a new `Event` (for example) entity with all of the `Record` and `UsNyRecord` fields, and delete the corresponding `Record and UsNyRecord` entities in the same atomic transaction.

Naming options include `Event`, `Case`, `Episode`, `Matter`, `Charge`, `Issue`, `Entry`, `Listing`, `Filing`.

*Approach 2: Migrate-in-place*
Alternatively, we can keep the name `Record` and migrate in-place.

(a) One approach to doing so would be to change the field names in the entity model for the 14x fields described in the top comment on this issue. However, modifying these names would both involve many more changes throughout the codebase, as well as a likely reduction in readability / intuitiveness of the names.

(b) A second approach would be to:
1. Migrate these fields to the new `Snapshot` entity type, without changing `Record`/`UsNyRecord`
2. Also migrate several `Record`-specific fields such as `created_on` and `updated_on` to `Snapshot`, temporarily
3. Delete all `UsNyRecord` entities, and the model
4. Add the new fields to the `Record` model
5. Migrate the new fields back to the `Record` model from the `Snapshot` entities (since the `UsNyRecord` entities that data came from are gone)
6. Delete the fields in `Snapshot` that are `Record`-specific (those described in 2 above)

**Recommendation**
I think 2a is hairy, and 2b is fragile. Though it feels hacky to me, I'd suggest we take Approach 1 and rename `Record`. Because of the policy change that's instigating this, we should never have to do it again. 

I'd suggest renaming to `Charge`, but am comfortable with most of the names listed above if others have strong opinions.

@jessex - thoughts?

**Comment by jessex** [comment]
When I started reading through this, before getting all the way to the end, my initial thought was to do what I think is a simpler version of 2b: write all of the `UsNyRecord` fields into an isolated `TempRecord[SomePostfixLikeTheIssueNumber]` entity type, then drop all `UsNyRecord` entities, write all of the fields from the temporary entity type into `Record`, then drop all the temp record entities. 

My nervousness around approach 1 is that it's not clear to me that the policy change is going to be enough to prevent an upward migration in the future. How confident can we be that we'll just get it right going forward without totally polluting the `Record` model by playing things conservative? I agree it's elegant for this particular use case wherein we are completely draining the subtype of all of its fields, but if this were to happen in a future scenario where that were not quite the case, we would have to pursue a different route. 

(I also quite like the name `Record` but would yield to Oliver's insight and experience on a rename if we went that route.)

**Comment by cawarren** [comment]
Definitely a more elegant / reusable migration approach, though it means the migration will be two-pass instead of one.

I'm not sure that we can establish a brightline on where to put different fields / whether `Record` is likely to get polluted unless we do a proper survey of the inmate locators. Once we know what fields are out there and how many are reused between states, we can draw a line that seems sane. (I'm not mentioning jail rosters both because they're tougher to survey, and because their fields seem much more consistent than the inmate locators' do.)

I've started one, will share it when it has enough info to start being useful in it.

**Comment by jessex** [comment]
I'm okay with a "two-pass" migration if it means a more elegant outcome, especially considering that our current level of operations means we can afford the longer migration cycle.

You're right on the point about the brightline. We have to feel it out and we have to keep a close eye on it over time, but I think that means that we should not assume that this is the only time we would need to do a rename. To me it says that we have enough uncertainty that we should strive for the best outcome, and I think the best outcome is one in which we don't have to rename one of our entities for the sake of migration.

_Having said that_, if you and @ohinds-vera believe that the `Record` entity is misnamed as is, then let's go with your first approach anyway and leverage that as a free move.

**Comment by cawarren** [comment]
Curious for @ohinds-vera 's read - IIRC during one of our weeklies, we talked about how it wasn't a perfect name given what we're using it for, but no better one came to mind either (unlike with `Inmate` / `Person`). 

If any of the options above (or something else) seem better, then great - we get a pass on this one. If not I'll go ahead with the more long-term migration approach.

**Comment by ohinds-vera** [comment]
Thanks for diving in on this @cawarren! You do recall correctly about the conversation we had about 'Record' as a name. I think the reason nothing is else fits better is that it represents an entity without a name (that I know of) in our criminal justice system. If we really want to be sure, I can go talk to some Vera folks who might know if it does?

I like @jessex suggestion on the simple two-pass migration. That seems like a reusable approach and I agree that if a rename is not necessary, this is the way to go.

**Comment by cawarren** [comment]
Stellar, thanks both.

I'm going to implement this as the two-pass approach.

**Comment by cawarren** [comment]
Releasing this for the moment so I don't block critical path, but I do hope to sit down and get back into the weeds sometime soon. Have just been buried in docs this week (in a good way!)

**Comment by cawarren** [comment]
I've just uploaded a slightly-cleaned-up version of the work I had so far on this. It's in the branch `issue-63-migration`. 

It implements all of the changes discussed above, as well as a couple of minor field names that were bugging me (`birthday` becomes `birthdate`, `last_name` becomes `surname`), but think of it as scaffolding rather than PR-ready.

Quick notes:

- Expect a lot of kinks to be worked through. I don't have GCloud on the PC I'm working on at the moment, so it hasn't been tested in its current state (even with the local devserver) - a lot is probably broken, but hopefully they're mostly minor fixes.
- Relatedly, there aren't tests at the moment. Think of this as a scaffold of how you can implement migration, with some rough edges and testing still needed.
- There are more elegant ways to handle copying all of the fields over as done in the `data_migration` module at the moment (for example, see some of what's done in `ingest.us_ny.us_ny_scraper:compare_and_set_snapshot`). If you try for something more elegant, be a little careful. A lot is the same, but some fields during the migration are constructed from different field names on the old entities, or from multiple old entities to create one new one (e.g., Snapshots pull in some info from the old `InmateFacilitySnapshot`, and a lot from the old `UsNyRecord`).

**Comment by cawarren** [comment]
Oh, and one other thing - a few changes have to be made in between pass 1 and pass 2 of the migration. The logging after pass 1 details them, but reproducing here as well:

- Delete the fields marked in recividiz_data/ingest/us_ny/us_ny_record.py
- Update the current indices for UsNyRecord or Record in index.yaml
- Uncomment new Record fields in
                           recividiz_data/ingest/models/record.py

**Comment by jessex** [comment]
Thanks a lot for the leg up here, @cawarren! Can you fill in more detail on the second bullet point regarding indices, though? Is it just updating indexed fields whose names and/or locations have changed?
