### ISSUE TITLE
Come up with release version numbering system

### ISSUE THREAD

**Issue by arian487** [Recidiviz/recidiviz-data#646]
Travis deploys are for now set up to release anything tagged with va.b.c, we need to decide on a standard.

**Comment by jessex** [comment]
https://semver.org/

![](https://i.imgflip.com/2rc4lp.jpg)

**Comment by arian487** [comment]
Yeaaaa this is an area where I (and most other googlers) are woefully outdated on.  I've never had to deal with releases outside of Google, and internally things sorta just magically work so I'm more than happy to be taught what the outside conventions are.

**Comment by jessex** [comment]
Let's go with SemVer. It's fairly well standard in the open source community. That website explains it as succinctly as I could, so let me know if you have any questions or concerns.

**Comment by arian487** [comment]
Alright, done.
