### ISSUE TITLE
consider scraping historical booking / release dates

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#708]
EagleAdvantage has a 'History' section that lists dates:
```xml
<d4p1:string>book:9/7/2009,release:7/16/2018</d4p1:string>
<d4p1:string>book:11/8/2008,release:7/16/2018</d4p1:string>
<d4p1:string>book:7/10/2009,release:7/16/2018</d4p1:string>
```

It seems common for probation/parole (here all the release dates are the same). There's currently no way to store this in our database.

**Comment by zdg2102** [comment]
Replacing this with #1146
