### ISSUE TITLE
schema additions

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#719]
From #707:
 - Add column Charge.charge_notes
 - Add enum value CourtType.CIVIL
 - Add enum value ChargeStatus.REVOKED

From #723:
 - Add column Bond.BOND_AGENT (BOND_AGENCY? BONDSMAN?)

**Comment by ohinds** [comment]
Ah right, you weren't around when jasmine got back to me about surety. Apparently this means different things in different places, so we're going to call that 'secured'. I do like the idea of adding a bond agent field though.

**Comment by zdg2102** [comment]
`charge_notes` and `bond_agent` were added in #747

`CourtType.CIVIL` was added in #753

`ChargeStatus.REVOKED` is part of community supervision, so it'll be covered by #400

And the changes to `BondType` and `BondStatus` will be covered by #741
