### ISSUE TITLE
Consider stripping punctuation and special characters from strings before doing enum mapping.

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#733]
To prevent things like:
    'ASIAN / PACIFIC ISLANDER': Race.ASIAN,
    'ASIAN / PACIFIC ISLANDER/': Race.ASIAN,

**Comment by KareemG** [comment]
I've run into a similar case, where the normalize function (seen in #756) isn't enough . For example:

'NO BOND - MUST SEE PRETRIAL': BondType.NO_BOND,
'NO BOND - SENTENCED': BondType.NO_BOND,

A solution I was thinking about was refactoring from a 1-1 enum_mapping to enum_predicates (or maybe support both?). So maybe something like:
```
_DATA_MASSAGER = {
    ChargeStatus.PENDING: [
        lambda x : x == 'OPEN',
    ],
    BondType.CASH: [
        lambda x : x == 'FULL CASH',
    ],
    BondType.NO_BOND: [
        lambda x : x.startswith('NO BOND'),
    ]
}
```

I was thinking this might also simplify the manual charge info manipulations seen in us_in_vigo, but perhaps it needs more use cases.
