### ISSUE TITLE
restructure enum overrides

### ISSUE THREAD

**Issue by jamwalla** [Recidiviz/recidiviz-data#816]
2 issues came up with our current enum overrides setup: it would be nice to specify that the same string maps to an enum for one field but `None` for another field; it would be nice to specify that the same string maps to two different enum values. We rely too much on the type of enum value for this process.

Instead, we want a nested object, like
```python
{Race: {'A': Race.ASIAN}, ChargeClass: {'A': None}}
```

In fact, we'll make it an object.
```python
overrides = EnumOverrides.Builder()
overrides.add('A', Race.ASIAN)
overrides.ignore(ChargeClass, 'A')
return overrides.build()
```

**Comment by jessex** [comment]
I like the builder option! We can hammer this out in code review of course, but I think builders are best when they ready fluidly, e.g.
```
return EnumOverrides.Builder()
        .add('A', Race.Asian)
        .ignore(ChargeClass, 'A')
        .build()
```

**Comment by colincadams** [comment]
@jessex I agree I like when each method from the builder returns itself so that you can chain them nicely, but during our group discussion I think @zacharylawrence  mentioned that this is atypical in python?

**Comment by jessex** [comment]
It's true that the builder pattern is a bit atypical, largely because you have named parameters available. I was responding mostly to that builder example in the description which I think would be improved by making it chainable, and if you're pursuing a builder in Python anyway then I don't yet know of a great reason that you wouldn't make it more chainable. I could be way wrong though!

**Comment by jessex** [comment]
Ah, that's fair. Frustrating, but fair.

**Comment by ohinds** [comment]
Here's a related issue that results in a lot of `populate_data` overrides:

I get BondType: 'PENDING - WAITING TO SEE MAGISTRATE', that ain't a BondType, that's a BondStatus, so I would love a way to map that string to BondStatus.PENDING without doing a sad, seemingly unnecessary string match and nothing else in `populate_data`.

**Comment by jamwalla** [comment]
One solution could look like:
```python
is_pending(s): s.startswith('PENDING')
overrides.remap(BondType, is_pending, BondStatus.PENDING)
```
This could be simpler, e.g. if we wanted to narrow this down to substring matches; or it could be more complex, e.g. if we wanted to map to different BondStatuses depending on the rest of the string.

@arian487 had another idea for how this should look.

**Comment by arian487** [comment]
Mine is basically identical to James' solution except instead of using a lambda, I think using a regex could be cleaner?

**Comment by ohinds** [comment]
Seems like you would need:
overrides.remap(BondType, r'PENDING*', BondStatus.PENDING)
to detect 'PENDING' just at the start?

Then, do we need to escape special characters in the equality case? or will the 'r' strings allow us to tell when we use straight equality versus a regex search.

**Comment by colincadams** [comment]
I don't believe it's possible to tell the difference between `r'x'` strings and `'x'` strings. It's just syntactic sugar for how the escaping works and both end up creating str objects.

I think I'd lean towards the lambda for readability/flexibility reasons and then if a scraper writer wants to use regex they can just have their lambda call `re` but I don't feel that strongly.

**Comment by zacharylawrence** [comment]
@jamwalla Also, just reminding here that we need to make sure to update: https://github.com/Recidiviz/recidiviz-data/tree/master/recidiviz/tools/scraper_template#resolving-enum-parsing-errors
