### ISSUE TITLE
Update regions_manifest with new config info

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#84]
_This is part of ingest generalization work_

Background:
The `region_manifest.yaml` file is used to store configuration info for each region we intend to scrape. It's currently missing several fields we will need long-term.

Scope of work:
- Add ‘scraper_package’ to regions_manifest (mapping to the scraper for that region)
- Add timezone to manifest
- Update `scrape_queue_name` to `queues`, and make it a list (for `us_ny` this will just be one entry, the current `us-ny-scraper` queue)
- Update the `scraper/utils/regions.py` file to make the new fields available, and update `scrape_queue_name` to a list of queues

**Comment by jessex** [comment]
As noted by @ohinds-vera in our recent meeting, some regions may require configuration which is non-standard. We should include the ability to provide dynamic/region-specific configuration alongside standard key-value pairs in the manifest as part of this issue.

**Comment by jessex** [comment]
@cawarren: is the timezone here meant to be the timezone of the region (assuming the region is entirely in one timezone) to line up with business hours?

**Comment by cawarren** [comment]
@jessex - yes, that's right - this is mainly to help us with timing scraping to off-peak hours.
