### ISSUE TITLE
Clean up ingest test coverage

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#89]
_This is part of ingest generalization work_

This is a cleanup task, intended to occur after the major changes involved in ingest generalization (otherwise, much of what gets new tests will be removed / majorly renovated, and require new tests again).

After all other generalization work is done (it can be tracked in issue #90), add test coverage for remaining uncovered components of the `ingest` system (including `us_ny` scraper).

**Comment by jessex** [comment]
You know, as engineering practice, I think it would be better, albeit more difficult now, to try to fill out test coverage as we go. With issues that extract logic from one place into another, or that create an interface where there is today only implementation, or that add new functionality--more or less all of the issues we've filed for the generalization work--having test coverage from the jump reduces the likelihood of bugs in a number of ways: shorter feedback loop, less context switching, less context loss. 

As long as we are testing only in scope of the issue being worked on, I don't think we'll have much test churn. And if there _is_ test churn, you could argue that it's even more important to have incremental test coverage improvement from issue to issue, as a sort of historical record of the impact of each commit.

**Comment by cawarren** [comment]
Sorry, I should have been clearer - most of the issues mentioned in the tracking bug have an explicit item 'Add test coverage', for the ones where they're not making a one-line change.

I think we're on the same page here - all of those should build test coverage of the portion their work pertains to. This bug is only for clean-up (that is, after all of those are done, see where we still don't have coverage and go add it there).

**Comment by jessex** [comment]
Ah, perfect. Same page. Thanks for filing all of these so diligently, @cawarren!

**Comment by jessex** [comment]
This was closed by #134 and also #148.
