### ISSUE TITLE
us_mo_cape_girardeau enum errors

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#947]
```
('us_mo_cape_girardeau', 'Race', 'A'),
```

**Comment by colincadams** [comment]
@jamwalla or @arian487 do we think this belongs in the global map?

**Comment by jamwalla** [comment]
We said no before, but I kinda think it should; I don't know what else it could be

**Comment by colincadams** [comment]
I guess it could be `ASIAN` or `AMERICAN INDIAN / ALASKA NATIVE`?

**Comment by arian487** [comment]
IMO this should detfinitely be per region.  I suspect it'll be Asian in most places but we definitely don't want to be wrong about that, I'm adding it as en enum override everywhere I see it and attempting to verify on the website.
