### ISSUE TITLE
Should we limit requests to one per task?

### ISSUE THREAD

**Issue by ohinds-vera** [Recidiviz/recidiviz-data#97]
In creating the Vermont scraper, there will be three requests required to build each Person. I can see arguments for making those requests in a single task or having three separate tasks with one request each. 

Single task:
- won't have to pass the content of preceding requests through to each subsequent task, or store it for later resume.
- having all data gathering atomic at this level prevents the edge case where a resumed queue contains stale data from one of the requests. 

Multiple tasks:
- aligns with the intuitive definition of 'task'.
- prevents repeating completed requests on retry if a later task fails.  

Thoughts?

**Comment by jessex** [comment]
My intuition, without having had the chance to play with the Vermont system yet, is to go with permitting multiple web requests in a single ingest/scraper task. In response to the two points in favor of mapping requests to tasks one-to-one:
* "aligns with the intuitive definition of 'task'."
The main question here is how to align a tree of requests (which all of these source data systems effectively model, with different depths and cardinality and other traits) to a task queue system. You could argue that each individual node in that tree is its own conceptual task, especially if there's a way to model the parent-child relationship, such as by passing data from the parent task to the child. You could also argue, though, that depending on the structure of the tree, a task matches to a subtree that represents a given individual. I'm not sure it's clear cut.
* "prevents repeating completed requests on retry if a later task fails."
This doesn't strike me as as big of a technical pro as the pros noted for permitting multiple requests in an atomic task. We can (and do) make use of operational tooling to see the rate and volume of request failure and can continue to invest in that area. But performing message passing of very sensitive data between distinct tasks, while addressing edge cases you have pointed out, seems much more complex and opens up a larger attack surface.

So in the question between "thin" and "thick" tasks, I do think it's important to allow flexibility and experimentation as we expand into more source data systems, but I think in the long term it is more important to be consistent in use of one pattern. In my mind, I think we'll find it technically simpler go the "thick" route and perform multiple requests within a single task where those requests compose a single Record.

I don't think it's a simple answer, though!

**Comment by cawarren** [comment]
Hmmm, I lean the other way, but maybe for a more naive reason - I really like the notion that any SWE working anywhere on the project can assume that the scraping queue rate is a 1:1 translation to our ratelimiting of scraping for that region. And that we can depend entirely on GCP to enforce it, rather than something homegrown.

So if you change the scrape queue rate, you're also changing the ratelimiting against that region's roster / inmate search system - and by the same amount. No weird multipliers or looking up per-scraper documentation somewhere to understand what the 'true' rate limit is. Relatedly, I worry that once we start to break that barrier, more trouble follows (e.g. some tasks for us_tn include 3x requests, others 5x - so now what exactly is our QPS against TN? And how to do change it reliably?)

**Comment by jessex** [comment]
Mm, that's a very good point, @cawarren.

@ohinds-vera: in the Vermont case specifically, how complex does the navigation code get if we throttle each task to one request?

**Comment by ohinds-vera** [comment]
Good comments, @jessex and @cawarren, 

I think I lean towards 1:1 task/request due to the rate-limiting simplicity argument. Let's see how long it takes us to run into a case where that's just too cumbersome. 

@jessex, it won't complicate things much logic-wise. It actually is a bit simpler in that each task will have the canned structure of:
1) build a request from input data
2) make and validate request
3) parse response
4) fire off the next task

**Comment by jessex** [comment]
Sounds good, let's go in this direction for now. Okay to close this issue as we are under agreement, or do we want to make sure this gets documented somewhere in the ingest docs?

**Comment by jessex** [comment]
Closing this out. The decision point here will be documented as part of #56, noted there.
