### ISSUE TITLE
JailTracker scraper not catching 'max-requests-for-timeperiod' error early enough

### ISSUE THREAD

**Issue by yentangen** [Recidiviz/recidiviz-data#982]
JailTracker sends many endpoint calls to build an inmate's profile (GetInmate, GetCases, GetCharges, GetImage, etc.) and each call has a possibility of returning **{'error': 'max-requests-for-timeperiod'}**.

While developing for us_ky_fulton I came across the following error when running the scraper:
Command:
`python -m recidiviz.tools.run_scraper --region us_ky_fulton --run_forever`

Stacktrace:

> INFO:root:Sleeping 1 seconds before sending another request
> INFO:root:***
> INFO:root:Running task 208 of infinite tasks
> INFO:root:Fetching content with endpoint: https://omsweb.public-safety-cloud.com/jtclientweb//(S(b14slzsl4knx5wzzp0pb3r0s))//(S(b14slzsl4knx5wzzp0pb3r0s))/JailTracker/GetCharges
> /Users/yentangen/.local/share/virtualenvs/recidiviz-data-SPJXWTXh/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> INFO:root:Scraping data for us_ky_fulton and endpoint: https://omsweb.public-safety-cloud.com/jtclientweb//(S(b14slzsl4knx5wzzp0pb3r0s))//(S(b14slzsl4knx5wzzp0pb3r0s))/JailTracker/GetCharges
> {'error': 'max-requests-for-timeperiod'}
> Traceback (most recent call last):
>   File "/Users/yentangen/projects/recidiviz-data/recidiviz/tools/run_scraper.py", line 77, in run_scraper
>     run_scraper_for_region(regions.get_region(region_code), args)
>   File "/Users/yentangen/projects/recidiviz-data/recidiviz/tools/run_scraper.py", line 117, in run_scraper_for_region
>     getattr(scraper, method)(request)
>   File "/Users/yentangen/projects/recidiviz-data/recidiviz/ingest/scrape/base_scraper.py", line 191, in _generic_scrape
>     content, task, request.ingest_info or IngestInfo())
>   File "/Users/yentangen/projects/recidiviz-data/recidiviz/ingest/scrape/vendors/jailtracker/jailtracker_scraper.py", line 209, in populate_data
>     task.custom[self._PERSON]['data'])
> KeyError: 'data'
> 
> INFO:root:***
> INFO:root:The following regions raised errors during scraping: ['us_ky_fulton']

**Note: the "{'error': 'max-requests-for-timeperiod'}" before the Traceback was manually inserted by myself.**

_KeyError: 'data'_ is not specific and error handling should be more verbose regarding the response it received. I propose the error raising in the block of the following link
https://github.com/Recidiviz/recidiviz-data/blob/master/recidiviz/ingest/scrape/vendors/jailtracker/jailtracker_scraper.py#L293

to be moved further up to around the following area:
https://github.com/Recidiviz/recidiviz-data/blob/bd347e0a95cd058b5767748cfd737f2fbce713d2/recidiviz/ingest/scrape/vendors/jailtracker/jailtracker_scraper.py#L207

**Comment by KareemG** [comment]
+1, also ran into this. Ended up printing out 'task' in populate_data to find out what was happening.

**Comment by yentangen** [comment]
BTW I'd be happy to make the code change if a 20%-er is allowed to do so :)

**Comment by jessex** [comment]
Please do, @yentangen!

**Comment by yentangen** [comment]
PR created:
#1004
